// Mocks generated by Mockito 5.4.6 from annotations
// in web_browser/test/home/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i4;
import 'package:state_notifier/state_notifier.dart' as _i6;
import 'package:web_browser/home/home_page_state.dart' as _i2;
import 'package:web_browser/home/home_page_view_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomePageState_0 extends _i1.SmartFake implements _i2.HomePageState {
  _FakeHomePageState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomePageViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomePageViewModel extends _i1.Mock implements _i3.HomePageViewModel {
  MockHomePageViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i5.dummyValue<_i4.Ref>(this, Invocation.getter(#ref)),
          )
          as _i4.Ref);

  @override
  _i2.HomePageState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeHomePageState_0(this, Invocation.getter(#state)),
          )
          as _i2.HomePageState);

  @override
  set state(_i2.HomePageState? newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  _i2.HomePageState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeHomePageState_0(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i2.HomePageState);

  @override
  void runBuild() => super.noSuchMethod(
    Invocation.method(#runBuild, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.RemoveListener listenSelf(
    void Function(_i2.HomePageState?, _i2.HomePageState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listenSelf, [listener], {#onError: onError}),
            returnValue: () {},
          )
          as _i6.RemoveListener);

  @override
  bool updateShouldNotify(
    _i2.HomePageState? previous,
    _i2.HomePageState? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
